name = "Cobaltmons"
author = "Jeef"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bf531b35d5b83774e47b40724b6541677703ddb50f0f444b7ee379bb3765389"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
datapack-folder = "global_packs/required_resources"
resourcepack-folder = "global_packs/required_resources"
