name = "Cobaltmons"
author = "Jeef"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0ee498c9b3e6ceba104d0828a2b0862cf333786127e86abf870afd63157e834"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
datapack-folder = "global_packs/required_resources"
resourcepack-folder = "global_packs/required_resources"
